# Libraries of Python
# Random module - 
# This module implements pseudo-random number generators for various distributions.
import random # Doc note: `random` uses pseudo-random algorithms (deterministic sequence from a seed).

coin = random.choice(["Heads","Tails"]) # Doc note: `choice(seq)` returns one element from a non-empty sequence; empty seq raises IndexError.
# Doc note: For security-sensitive randomness, prefer `secrets` over `random`.
print(coin)

num = random.randint(1,10) # Doc note: `randint(a, b)` returns a random integer N where a <= N <= b (both bounds inclusive). Alias for randrange(a, b+1).
print(num)

cards = ["Jack","King","Queen","Ace"]
random.shuffle(cards) # Doc note: `shuffle(seq)` shuffles the sequence in-place (modifies the original list, returns None).
print(cards)

import statistics # Doc note: `statistics` provides functions for mean, median, mode, stdev, variance and more on real numeric (Real-valued) data.
""" 
Averages and measures of central location
These functions calculate an average or typical value from a population or sample.

mean()->Arithmetic mean (“average”) of data.
fmean()->Fast, floating-point arithmetic mean, with optional weighting.
geometric_mean()->Geometric mean of data.
harmonic_mean()->Harmonic mean of data.
kde()Estimate the probability density distribution of the data.
kde_random()Random sampling from the PDF generated by kde().
median()Median (middle value) of data.
median_low()Low median of data.
median_high()High median of data.
median_grouped()Median (50th percentile) of grouped data.
mode()Single mode (most common value) of discrete or nominal data.
multimode()List of modes (most common values) of discrete or nominal data.
quantiles()Divide data into intervals with equal probability.

Measures of spread
These functions calculate a measure of how much the population or sample tends to deviate from the typical or average values.

pstdev()Population standard deviation of data.
pvariance()Population variance of data.
stdev()Sample standard deviation of data.
variance()Sample variance of data.
Statistics for relations between two inputs
These functions calculate statistics regarding relations between two inputs.
covariance()Sample covariance for two variables.
correlation()Pearson and Spearman’s correlation coefficients.
linear_regression()Slope and intercept for simple linear regression.
"""

print(statistics.mean([5,6,8,3,5]))

import sys # Doc note: `sys` gives access to interpreter variables and functions. `sys.argv` holds CLI arguments as a list (argv[0] = script name, argv[1] = first user arg).
print("Hello, my name is", sys.argv[1]) #The list of command line arguments passed to a Python script. argv[0] is the script name (it is operating system dependent whether this is a full pathname or not). 
# If the command was executed using the -c command line option to the interpreter, argv[0] is set to the string '-c'. If no script name was passed to the Python interpreter, argv[0] is the empty string.

if len(sys.argv) < 2:
    sys.exit("Too less arguments!") # Doc note: `sys.exit(msg)` raises SystemExit — prints msg to stderr and terminates the program immediately.
elif len(sys.argv) > 2:
    sys.exit("Too may arguments!")
print("hello, my name is", sys.argv[1])
import cowsay # Doc note: `cowsay` is a third-party module (install via `pip install cowsay`); `cowsay.cow(msg)` prints ASCII cow art with the message.
if len(sys.argv) == 2:
    cowsay.cow("hello, " + sys.argv[1])



